export const OS_CONFIG = {
  Windows: {
    versions: [
      '11', 
      '10', 
      '8.1',
      '8', 
      '7', 
      'Vista', 
      'XP', 
      '2000',
      'ME',
      '98',
      '95',
      'NT 4.0',
      'NT 3.5',
      'NT 3.1',
      '3.1',
      '2.0',
      '1.0',
    ],
    defaultMessage: 'Your PC will restart several times. Sit back and relax.',
  },
  macOS: {
    versions: [
      '15',
      'Sonoma', 
      'Ventura', 
      'Monterey',
      'Big Sur',
      'Catalina',
      'Mojave',
      'High Sierra',
      'Sierra',
      'El Capitan',
      'Yosemite',
      'Mavericks',
      'Mountain Lion',
      'Lion',
      'Snow Leopard',
      'Leopard',
      'Tiger',
      'Panther',
      'Jaguar',
      'Puma',
      'Cheetah',
      'Mac OS 9',
      'Mac OS 8',
      'System 7',
      'System 6',
      'System 5',
      'System 4',
      'System 3',
      'System 2',
      'System 1',
    ],
    defaultMessage: 'Your Mac will restart to complete the installation.',
  },
} as const;

export const OS_LIST = Object.keys(OS_CONFIG) as (keyof typeof OS_CONFIG)[];
